imports:
  - php

filter:
  excluded_paths:
    - 'src/Resources/*'
    - 'tests/*'

tools:
  sensiolabs_security_checker: true
  php_sim: true
  php_pdepend: true
  php_analyzer: true

build:
  nodes:
    coverage:
      tests:
        override:
          - command: 'composer install && composer test'
            coverage:
              file: coverage.xml
              format: clover
